name: Build and publish website

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build site
      uses: actions/jekyll-build-pages@v1

    - name: Push to FTP
      uses: dennisameling/ftp-upload-action@v1
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        secure: false
        local_dir: ./_site/
